# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---

/**:
    ros__parameters:

        general:
            camera_model:               'zedm'
            camera_name:                'zedm'

        depth:
            min_depth:                  0.3            # Min: 0.1, Max: 3.0 - Default 0.3 - Note: reducing this value wil require more computational power and GPU memory
            max_depth:                  10.0            # Max: 20.0

        pos_tracking:
            imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only the optical odometry will be used.
            publish_imu_tf:             true            # enable/disable the static IMU TF broadcasting

        sensors:
            sensors_image_sync:         false           # Synchronize Sensors messages with latest published video/depth message
            sensors_pub_rate:           200.            # frequency of publishing of sensors data. MAX: 400. - MIN: grab rate
            qos_history:                1               # '1': KEEP_LAST - '2': KEEP_ALL
            qos_depth:                  1               # Queue size if using KEEP_LAST
            qos_reliability:            1               # '1': RELIABLE - '2': BEST_EFFORT - 
            qos_durability:             2               # '1': TRANSIENT_LOCAL - '2': VOLATILE
